/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HouseDemolitionRouteImport } from './routes/house-demolition'
import { Route as RubbishRemovalRouteImport } from './routes/rubbish-removal'
import { Route as StripOutRouteImport } from './routes/strip-out'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as ThankYouHouseDemolitionRouteImport } from './routes/thank-you-house-demolition'
import { Route as ThankYouRubbishRemovalRouteImport } from './routes/thank-you-rubbish-removal'
import { Route as ThankYouStripOutRouteImport } from './routes/thank-you-strip-out'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseDemolitionRoute = HouseDemolitionRouteImport.update({
  id: '/house-demolition',
  path: '/house-demolition',
  getParentRoute: () => rootRouteImport,
} as any)
const RubbishRemovalRoute = RubbishRemovalRouteImport.update({
  id: '/rubbish-removal',
  path: '/rubbish-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const StripOutRoute = StripOutRouteImport.update({
  id: '/strip-out',
  path: '/strip-out',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouHouseDemolitionRoute = ThankYouHouseDemolitionRouteImport.update({
  id: '/thank-you-house-demolition',
  path: '/thank-you-house-demolition',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRubbishRemovalRoute = ThankYouRubbishRemovalRouteImport.update({
  id: '/thank-you-rubbish-removal',
  path: '/thank-you-rubbish-removal',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouStripOutRoute = ThankYouStripOutRouteImport.update({
  id: '/thank-you-strip-out',
  path: '/thank-you-strip-out',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/house-demolition': typeof HouseDemolitionRoute
  '/rubbish-removal': typeof RubbishRemovalRoute
  '/strip-out': typeof StripOutRoute
  '/thank-you': typeof ThankYouRoute
  '/thank-you-house-demolition': typeof ThankYouHouseDemolitionRoute
  '/thank-you-rubbish-removal': typeof ThankYouRubbishRemovalRoute
  '/thank-you-strip-out': typeof ThankYouStripOutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/house-demolition': typeof HouseDemolitionRoute
  '/rubbish-removal': typeof RubbishRemovalRoute
  '/strip-out': typeof StripOutRoute
  '/thank-you': typeof ThankYouRoute
  '/thank-you-house-demolition': typeof ThankYouHouseDemolitionRoute
  '/thank-you-rubbish-removal': typeof ThankYouRubbishRemovalRoute
  '/thank-you-strip-out': typeof ThankYouStripOutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/house-demolition': typeof HouseDemolitionRoute
  '/rubbish-removal': typeof RubbishRemovalRoute
  '/strip-out': typeof StripOutRoute
  '/thank-you': typeof ThankYouRoute
  '/thank-you-house-demolition': typeof ThankYouHouseDemolitionRoute
  '/thank-you-rubbish-removal': typeof ThankYouRubbishRemovalRoute
  '/thank-you-strip-out': typeof ThankYouStripOutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/house-demolition'
    | '/rubbish-removal'
    | '/strip-out'
    | '/thank-you'
    | '/thank-you-house-demolition'
    | '/thank-you-rubbish-removal'
    | '/thank-you-strip-out'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/house-demolition'
    | '/rubbish-removal'
    | '/strip-out'
    | '/thank-you'
    | '/thank-you-house-demolition'
    | '/thank-you-rubbish-removal'
    | '/thank-you-strip-out'
  id:
    | '__root__'
    | '/'
    | '/house-demolition'
    | '/rubbish-removal'
    | '/strip-out'
    | '/thank-you'
    | '/thank-you-house-demolition'
    | '/thank-you-rubbish-removal'
    | '/thank-you-strip-out'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HouseDemolitionRoute: typeof HouseDemolitionRoute
  RubbishRemovalRoute: typeof RubbishRemovalRoute
  StripOutRoute: typeof StripOutRoute
  ThankYouRoute: typeof ThankYouRoute
  ThankYouHouseDemolitionRoute: typeof ThankYouHouseDemolitionRoute
  ThankYouRubbishRemovalRoute: typeof ThankYouRubbishRemovalRoute
  ThankYouStripOutRoute: typeof ThankYouStripOutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house-demolition': {
      id: '/house-demolition'
      path: '/house-demolition'
      fullPath: '/house-demolition'
      preLoaderRoute: typeof HouseDemolitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rubbish-removal': {
      id: '/rubbish-removal'
      path: '/rubbish-removal'
      fullPath: '/rubbish-removal'
      preLoaderRoute: typeof RubbishRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strip-out': {
      id: '/strip-out'
      path: '/strip-out'
      fullPath: '/strip-out'
      preLoaderRoute: typeof StripOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you-house-demolition': {
      id: '/thank-you-house-demolition'
      path: '/thank-you-house-demolition'
      fullPath: '/thank-you-house-demolition'
      preLoaderRoute: typeof ThankYouHouseDemolitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you-rubbish-removal': {
      id: '/thank-you-rubbish-removal'
      path: '/thank-you-rubbish-removal'
      fullPath: '/thank-you-rubbish-removal'
      preLoaderRoute: typeof ThankYouRubbishRemovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you-strip-out': {
      id: '/thank-you-strip-out'
      path: '/thank-you-strip-out'
      fullPath: '/thank-you-strip-out'
      preLoaderRoute: typeof ThankYouStripOutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HouseDemolitionRoute: HouseDemolitionRoute,
  RubbishRemovalRoute: RubbishRemovalRoute,
  StripOutRoute: StripOutRoute,
  ThankYouRoute: ThankYouRoute,
  ThankYouHouseDemolitionRoute: ThankYouHouseDemolitionRoute,
  ThankYouRubbishRemovalRoute: ThankYouRubbishRemovalRoute,
  ThankYouStripOutRoute: ThankYouStripOutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
